// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using STYS.Infrastructure.EntityFramework;

#nullable disable

namespace STYS.Infrastructure.EntityFramework.Migrations
{
    [DbContext(typeof(StysAppDbContext))]
    [Migration("20260302121243_MakeKullaniciTesisSahiplikTesisIdNullable")]
    partial class MakeKullaniciTesisSahiplikTesisIdNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("dbo")
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("STYS.Binalar.Entities.Bina", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KatSayisi")
                        .HasColumnType("int");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("TesisId", "Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("Binalar", "dbo");
                });

            modelBuilder.Entity("STYS.Binalar.Entities.BinaYonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("BinaId", "UserId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("BinaYoneticileri", "dbo");
                });

            modelBuilder.Entity("STYS.Countries.Entities.Country", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Countries", "dbo");
                });

            modelBuilder.Entity("STYS.Iller.Entities.Il", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("Iller", "dbo");
                });

            modelBuilder.Entity("STYS.IsletmeAlanlari.Entities.IsletmeAlani", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BinaId", "Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("IsletmeAlanlari", "dbo");
                });

            modelBuilder.Entity("STYS.Kullanicilar.Entities.KullaniciTesisSahiplik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("TesisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TesisId");

                    b.HasIndex("UserId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("KullaniciTesisSahiplikleri", "dbo");
                });

            modelBuilder.Entity("STYS.OdaOzellikleri.Entities.OdaOzellik", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VeriTipi")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.HasIndex("Kod")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("OdaOzellikleri", "dbo");
                });

            modelBuilder.Entity("STYS.OdaOzellikleri.Entities.OdaOzellikDeger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deger")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OdaId")
                        .HasColumnType("int");

                    b.Property<int>("OdaOzellikId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OdaOzellikId");

                    b.HasIndex("OdaId", "OdaOzellikId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("OdaOzellikDegerleri", "dbo");
                });

            modelBuilder.Entity("STYS.OdaSiniflari.Entities.OdaSinifi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.HasIndex("Kod")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("OdaSiniflari", "dbo");
                });

            modelBuilder.Entity("STYS.OdaTipleri.Entities.OdaTipi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Kapasite")
                        .HasColumnType("int");

                    b.Property<int>("OdaSinifiId")
                        .HasColumnType("int");

                    b.Property<bool>("PaylasimliMi")
                        .HasColumnType("bit");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OdaSinifiId");

                    b.HasIndex("TesisId", "Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("TesisOdaTipleri", "dbo");
                });

            modelBuilder.Entity("STYS.OdaTipleri.Entities.TesisOdaTipiOzellikDeger", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Deger")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OdaOzellikId")
                        .HasColumnType("int");

                    b.Property<int>("TesisOdaTipiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("OdaOzellikId");

                    b.HasIndex("TesisOdaTipiId", "OdaOzellikId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TesisOdaTipiOzellikDegerleri", "dbo");
                });

            modelBuilder.Entity("STYS.Odalar.Entities.Oda", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<int>("BinaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("KatNo")
                        .HasColumnType("int");

                    b.Property<string>("OdaNo")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("TesisOdaTipiId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("YatakSayisi")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TesisOdaTipiId");

                    b.HasIndex("BinaId", "OdaNo")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("Odalar", "dbo");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.Tesis", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Adres")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Eposta")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("IlId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("IlId", "Ad")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0 AND [AktifMi] = 1");

                    b.ToTable("Tesisler", "dbo");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.TesisResepsiyonist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TesisId", "UserId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TesisResepsiyonistleri", "dbo");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.TesisYonetici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeletedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("TesisId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("TesisId", "UserId")
                        .IsUnique()
                        .HasFilter("[IsDeleted] = 0");

                    b.ToTable("TesisYoneticileri", "dbo");
                });

            modelBuilder.Entity("STYS.Binalar.Entities.Bina", b =>
                {
                    b.HasOne("STYS.Tesisler.Entities.Tesis", "Tesis")
                        .WithMany("Binalar")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("STYS.Binalar.Entities.BinaYonetici", b =>
                {
                    b.HasOne("STYS.Binalar.Entities.Bina", "Bina")
                        .WithMany("Yoneticiler")
                        .HasForeignKey("BinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bina");
                });

            modelBuilder.Entity("STYS.IsletmeAlanlari.Entities.IsletmeAlani", b =>
                {
                    b.HasOne("STYS.Binalar.Entities.Bina", "Bina")
                        .WithMany("IsletmeAlanlari")
                        .HasForeignKey("BinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bina");
                });

            modelBuilder.Entity("STYS.Kullanicilar.Entities.KullaniciTesisSahiplik", b =>
                {
                    b.HasOne("STYS.Tesisler.Entities.Tesis", "Tesis")
                        .WithMany()
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("STYS.OdaOzellikleri.Entities.OdaOzellikDeger", b =>
                {
                    b.HasOne("STYS.Odalar.Entities.Oda", "Oda")
                        .WithMany("OdaOzellikDegerleri")
                        .HasForeignKey("OdaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STYS.OdaOzellikleri.Entities.OdaOzellik", "OdaOzellik")
                        .WithMany("OdaDegerleri")
                        .HasForeignKey("OdaOzellikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Oda");

                    b.Navigation("OdaOzellik");
                });

            modelBuilder.Entity("STYS.OdaTipleri.Entities.OdaTipi", b =>
                {
                    b.HasOne("STYS.OdaSiniflari.Entities.OdaSinifi", "OdaSinifi")
                        .WithMany("OdaTipleri")
                        .HasForeignKey("OdaSinifiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STYS.Tesisler.Entities.Tesis", "Tesis")
                        .WithMany("OdaTipleri")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OdaSinifi");

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("STYS.OdaTipleri.Entities.TesisOdaTipiOzellikDeger", b =>
                {
                    b.HasOne("STYS.OdaOzellikleri.Entities.OdaOzellik", "OdaOzellik")
                        .WithMany()
                        .HasForeignKey("OdaOzellikId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STYS.OdaTipleri.Entities.OdaTipi", "TesisOdaTipi")
                        .WithMany("OdaOzellikDegerleri")
                        .HasForeignKey("TesisOdaTipiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OdaOzellik");

                    b.Navigation("TesisOdaTipi");
                });

            modelBuilder.Entity("STYS.Odalar.Entities.Oda", b =>
                {
                    b.HasOne("STYS.Binalar.Entities.Bina", "Bina")
                        .WithMany("Odalar")
                        .HasForeignKey("BinaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("STYS.OdaTipleri.Entities.OdaTipi", "TesisOdaTipi")
                        .WithMany("Odalar")
                        .HasForeignKey("TesisOdaTipiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Bina");

                    b.Navigation("TesisOdaTipi");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.Tesis", b =>
                {
                    b.HasOne("STYS.Iller.Entities.Il", "Il")
                        .WithMany("Tesisler")
                        .HasForeignKey("IlId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Il");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.TesisResepsiyonist", b =>
                {
                    b.HasOne("STYS.Tesisler.Entities.Tesis", "Tesis")
                        .WithMany("Resepsiyonistler")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.TesisYonetici", b =>
                {
                    b.HasOne("STYS.Tesisler.Entities.Tesis", "Tesis")
                        .WithMany("Yoneticiler")
                        .HasForeignKey("TesisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tesis");
                });

            modelBuilder.Entity("STYS.Binalar.Entities.Bina", b =>
                {
                    b.Navigation("IsletmeAlanlari");

                    b.Navigation("Odalar");

                    b.Navigation("Yoneticiler");
                });

            modelBuilder.Entity("STYS.Iller.Entities.Il", b =>
                {
                    b.Navigation("Tesisler");
                });

            modelBuilder.Entity("STYS.OdaOzellikleri.Entities.OdaOzellik", b =>
                {
                    b.Navigation("OdaDegerleri");
                });

            modelBuilder.Entity("STYS.OdaSiniflari.Entities.OdaSinifi", b =>
                {
                    b.Navigation("OdaTipleri");
                });

            modelBuilder.Entity("STYS.OdaTipleri.Entities.OdaTipi", b =>
                {
                    b.Navigation("OdaOzellikDegerleri");

                    b.Navigation("Odalar");
                });

            modelBuilder.Entity("STYS.Odalar.Entities.Oda", b =>
                {
                    b.Navigation("OdaOzellikDegerleri");
                });

            modelBuilder.Entity("STYS.Tesisler.Entities.Tesis", b =>
                {
                    b.Navigation("Binalar");

                    b.Navigation("OdaTipleri");

                    b.Navigation("Resepsiyonistler");

                    b.Navigation("Yoneticiler");
                });
#pragma warning restore 612, 618
        }
    }
}
