// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using STYS.Infrastructure.EntityFramework;

#nullable disable

namespace STYS.Infrastructure.EntityFramework.Migrations;

[DbContext(typeof(StysAppDbContext))]
[Migration("20260604183000_FazQ_CariKartBankaHesabiEntitySeed")]
partial class FazQ_CariKartBankaHesabiEntitySeed
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
    }
}
